new/1751534999_6541.eml:
- Work with documents
- Attachment requests
- Generic greetings
- Financial operations
- Mention of postponed call
new/1751226612_7126.eml:
- Work with documents
- Attachment requests
- Generic greetings
- Financial operations
new/1751459773_14774.eml:
- Financial operations
- Attachment requests
- Contests/prizes
- Explicit money amounts
new/1751215885_8181.eml:
- Financial operations
- Contests/prizes
- Link click requests
- Generic greetings
- Personal data requests
- Explicit money amounts
- Sender identification
new/1751217853_11656.eml:
- Urgency/threats
- Contests/prizes
- Confidentiality requests
new/1751259491_61596.eml:
- Contests/prizes
- Link click requests
- Urgency/threats
new/1751218514_12821.eml:
- Contests/prizes
new/1751297229_14050.eml:
- Generic greetings
- Sender identification
- Surveys and voting
- Link click requests
new/1751248886_44041.eml:
- Service notifications
- Surveys and voting
new/1751464133_19853.eml:
- Sender identification
- Personalized greetings
- Contests/prizes
- Urgency/threats
- Surveys and voting
- Explicit money amounts
- Confidentiality requests
new/1751536781_8623.eml:
- Surveys and voting
- Personalized greetings
new/1751271683_7850.eml:
- Contests/prizes
- Surveys and voting
- Work with documents
- Urgency/threats
new/1751222320_277.eml:
- Work with documents
- Generic greetings
- Attachment requests
- Financial operations
new/1751536781_8161.eml:
- Work with documents
- Sender identification
- Generic greetings
- Attachment requests
- Financial operations
- Explicit money amounts
new/1751532907_4403.eml:
- Product offers
- Personal data requests
- Service notifications
- Work with documents
- Confidentiality requests
- Financial operations
- Link click requests
new/1751297229_14389.eml:
- Personal data requests
- Service notifications
- Work with documents
- Generic greetings
- Urgency/threats
- Attachment requests
- Financial operations
- Sender identification
new/1751267519_449.eml:
- Generic greetings
- Attachment requests
- Financial operations
- Explicit money amounts
- Sender identification
- Work with documents
- Personal data requests
new/1751298279_16859.eml:
- Urgency/threats
- Sender identification
- Government impersonation
new/1751246516_40401.eml:
- Personal data requests
- Generic greetings
- Government impersonation
- Financial operations
- Sender identification
- Urgency/threats
new/1751291525_4433.eml:
- Colleague/authority impersonation
- Generic greetings
- Attachment requests
- Financial operations
- Explicit money amounts
- Sender identification
- Personal data requests
- Work with documents
new/1751237977_26588.eml:
- Generic greetings
- Link click requests
- Work with documents
- Sender identification
new/1751312309_1705.eml:
- Financial operations
- Colleague/authority impersonation
- Generic greetings
- Government impersonation
- Explicit money amounts
- Sender identification
new/1751535948_7223.eml:
- Product offers
- Colleague/authority impersonation
- Work with documents
- Link click requests
- Generic greetings
- Attachment requests
- Sender identification
new/1751267519_979.eml:
- Personalized greetings
- Urgency/threats
- Government impersonation
- Personal data requests
- Sender identification
- Link click requests
new/1751251325_48070.eml:
- Generic greetings
- Attachment requests
- Work with documents
- Government impersonation
- Confidentiality requests
- Urgency/threats
- Sender identification
new/1751230897_14208.eml:
- Technical issues
new/1751542189_396.eml:
- Technical issues
- Sender identification
new/1751296065_12945.eml:
- Attachment requests
- Urgency/threats
- Service notifications
- Technical issues
- Link click requests
new/1751253073_51830.eml:
- Financial operations
- Urgency/threats
- Sender identification
- Generic greetings
- Attachment requests
- No-confirmation requests
- Confidentiality requests
- Technical issues
- Service notifications
- Work with documents
new/1751255025_54692.eml:
- Technical issues
- Link click requests
- Security bypass requests
- Product offers
new/1751461728_16711.eml:
- Technical issues
- Link click requests
- Security bypass requests
- Product offers
new/1751527948_313.eml:
- Sender identification
- Service notifications
- Technical issues
- Attachment requests
- Generic greetings
- No-confirmation requests
- Link click requests
- Personal data requests
- Work with documents
new/1751534078_5364.eml:
- Work with documents
- Personalized greetings
- Sender identification
- Attachment requests
new/1751256321_56270.eml:
- Generic greetings
- Contests/prizes
- Explicit money amounts
- Sender identification
new/1751211141_685.eml:
- Work with documents
- Generic greetings
- Attachment requests
- Product offers
- Sender identification
new/1751219269_13391.eml:
- Generic greetings
- Mention of postponed call
- Product offers
- Sender identification
new/1751467906_23018.eml:
- Technical issues
- Personalized greetings
- Mention of postponed call
- Sender identification
- Link click requests
new/1751232880_17968.eml:
- Personalized greetings
- Mention of postponed call
new/1751386345_2123.eml:
- Personalized greetings
- Mention of postponed call
- Product offers
- Sender identification
- Link click requests
new/1751464133_19930.eml:
- Sender identification
- Service notifications
- Link click requests
new/1751467906_23686.eml:
- Personal data requests
- Personalized greetings
- Link click requests
new/1751226003_6243.eml:
- Service notifications
- Work with documents
- Attachment requests
- Generic greetings
- Government impersonation
new/1751239822_29212.eml:
- Service notifications
- Attachment requests
new/1751268180_1761.eml:
- Sender identification
- Work with documents
- Technical issues
- Attachment requests
- Generic greetings
- No-confirmation requests
- Service notifications
new/1751451147_6259.eml:
- Product offers
- Confidentiality requests
- Sender identification
new/1751227897_9606.eml:
- Work with documents
- Colleague/authority impersonation
- Sender identification
- Generic greetings
new/1751458726_13334.eml:
- Urgency/threats
- Sender identification
new/1751534078_5851.eml:
- Sender identification
- Work with documents
- HR messages
- Attachment requests
- Confidentiality requests
new/1751465079_20283.eml:
- Generic greetings
- Link click requests
- Service notifications
new/1751229616_12101.eml:
- Urgency/threats
- Product offers
- Service notifications
- No-confirmation requests
- Generic greetings
new/1751255669_55826.eml:
- Urgency/threats
- Personal data requests
- Personalized greetings
- Link click requests
- No-confirmation requests
- Service notifications
new/1751238593_27419.eml:
- Work with documents
- No-confirmation requests
- Generic greetings
- Attachment requests
- Financial operations
- Colleague/authority impersonation
- Sender identification
- Link click requests
new/1751544031_2357.eml:
- Work with documents
- No-confirmation requests
- Generic greetings
- Attachment requests
- Sender identification
new/1751236881_24779.eml:
- Urgency/threats
- Product offers
- Link click requests
- Sender identification
new/1751211766_1796.eml:
- Sender identification
- Surveys and voting
- Personalized greetings
new/1751253073_51597.eml:
- Work with documents
- Service notifications
- Attachment requests
- Generic greetings
- No-confirmation requests
- Sender identification
new/1751293859_8435.eml:
- Product offers
- Urgency/threats
- Surveys and voting
- Generic greetings
- Explicit money amounts
- Link click requests
- Contests/prizes
new/1751239278_28693.eml:
- Sender identification
- Surveys and voting
- Personalized greetings
new/1751530715_2712.eml:
- Urgency/threats
- Service notifications
new/1751536781_8007.eml:
- Surveys and voting
- Link click requests
- Colleague/authority impersonation
new/1751250081_46930.eml:
- Colleague/authority impersonation
- HR messages
- Generic greetings
- Link click requests
- Work with documents
- Sender identification
new/1751461728_16200.eml:
- HR messages
- Generic greetings
- Link click requests
- Sender identification
new/1751293272_7421.eml:
- HR messages
- Personalized greetings
- Sender identification
new/1751529826_1641.eml:
- Sender identification
- HR messages
- Link click requests
- Personalized greetings
- Work with documents
new/1751226612_7632.eml:
- HR messages
- Link click requests
new/1751217193_10753.eml:
- Urgency/threats
- HR messages
- Attachment requests
- Generic greetings
new/1751297229_14131.eml:
- Work with documents
- HR messages
- Attachment requests
- Generic greetings
- Sender identification
- Colleague/authority impersonation
new/1751534999_6096.eml:
- Colleague/authority impersonation
- Service notifications
- Personalized greetings
- Link click requests
new/1751469850_26911.eml:
- Attachment requests
- Sender identification
new/1751238593_27176.eml:
- Work with documents
- Service notifications
- Attachment requests
- Generic greetings
new/1751296065_12220.eml:
- Sender identification
- Service notifications
- Personalized greetings
new/1751467906_23723.eml:
- Sender identification
- Service notifications
- Personal data requests
- Personalized greetings
- Link click requests
new/1751385805_1075.eml:
- Personal data requests
- Urgency/threats
- Government impersonation
- Generic greetings
- Financial operations
- Explicit money amounts
- Link click requests
- Service notifications
- Sender identification
new/1751447933_3583.eml:
- Product offers
- Urgency/threats
- Contests/prizes
- Generic greetings
- Link click requests
new/1751224800_4395.eml:
- Product offers
- Contests/prizes
- Surveys and voting
- Link click requests
new/1751458726_13472.eml:
- Contests/prizes
- Generic greetings
- Surveys and voting
new/1751297757_15890.eml:
- Contests/prizes
- Explicit money amounts
new/1751463413_18070.eml:
- Service notifications
- Personal data requests
- Attachment requests
- Generic greetings
- Link click requests
- Sender identification
- Work with documents
new/1751297229_14319.eml:
- Sender identification
- Personal data requests
- Urgency/threats
- Service notifications
- Generic greetings
new/1751532907_4642.eml:
- Sender identification
- Service notifications
- Personal data requests
- Confidentiality requests
new/1751215175_7265.eml:
- Urgency/threats
- Colleague/authority impersonation
- Work with documents
- Link click requests
- Sender identification
new/1751534999_6317.eml:
- Sender identification
- HR messages
- Link click requests
new/1751292049_5865.eml:
- Product offers
- Generic greetings
- Explicit money amounts
- Sender identification
new/1751268180_1552.eml:
- Product offers
- Link click requests
new/1751255025_54762.eml:
- Personal data requests
- Attachment requests
- Generic greetings
- No-confirmation requests
new/1751531708_3144.eml:
- Product offers
- Attachment requests
- Generic greetings
- Confidentiality requests
- Work with documents
- Sender identification
new/1751464133_19460.eml:
- Generic greetings
new/1751225394_5743.eml:
- Sender identification
- Service notifications
- Work with documents
- Attachment requests
- Confidentiality requests
new/1751228462_10740.eml:
- Urgency/threats
- Product offers
- Personalized greetings
- Link click requests
- Financial operations
new/1751469183_25186.eml:
- Attachment requests
- Work with documents
- Generic greetings
- Sender identification
new/1751311662_318.eml:
- Technical issues
- Product offers
- Link click requests
- Sender identification
new/1751247748_42114.eml:
- Service notifications
- Personalized greetings
- Link click requests
new/1751299513_18310.eml:
- Confidentiality requests
- Sender identification
new/1751542189_809.eml:
- Work with documents
- Personal data requests
- Personalized greetings
- Urgency/threats
new/1751271683_7572.eml:
- Personal data requests
- Sender identification
- Colleague/authority impersonation
- Attachment requests
- Generic greetings
- Work with documents
new/1751531708_3377.eml:
- Sender identification
- Work with documents
- Colleague/authority impersonation
- Attachment requests
- Generic greetings
new/1751544031_2688.eml:
- Mention of postponed call
- Product offers
- Personalized greetings
- Sender identification
new/1751294383_9169.eml:
- Colleague/authority impersonation
- Generic greetings
- Explicit money amounts
- Sender identification
- Attachment requests
- Work with documents
new/1751468554_24240.eml:
- Service notifications
- Generic greetings
- No-confirmation requests
new/1751253073_51520.eml:
- Work with documents
- Generic greetings
- Urgency/threats
- Service notifications
- Personal data requests
- Attachment requests
- Confidentiality requests
- Sender identification
new/1751538547_10274.eml:
- Financial operations
- Urgency/threats
- Service notifications
- Link click requests
new/1751271683_7960.eml:
- Technical issues
- Service notifications
- Attachment requests
- Generic greetings
new/1751542189_412.eml:
- Product offers
- Explicit money amounts
- Link click requests
1755802200_139.eml:
- Colleague/authority impersonation
- Technical issues
- Generic greetings
- Service notifications
- Sender identification
- Link click requests
1755802200_142.eml:
- Sender identification
- Urgency/threats
- Technical issues
- Service notifications
- Link click requests
1755802200_147.eml:
- Work with documents
- Personalized greetings
- Product offers
- Sender identification
- Link click requests
- Attachment requests
1755802200_15.eml:
- Generic greetings
- Government impersonation
- Urgency/threats
- Link click requests
- Sender identification
1755802200_160.eml:
- Urgency/threats
- Colleague/authority impersonation
- Attachment requests
- Generic greetings
- Work with documents
- Financial operations
- Sender identification
1755802200_161.eml:
- Government impersonation
- Sender identification
- Generic greetings
1755802200_59.eml:
- Financial operations
- Personal data requests
- Urgency/threats
- Generic greetings
- Explicit money amounts
- Attachment requests
- Work with documents
- Sender identification
1755802200_81.eml:
- Colleague/authority impersonation
- No-confirmation requests
- Surveys and voting
- Generic greetings
- Sender identification
- Link click requests
1755802200_87.eml:
- Work with documents
- Urgency/threats
- Government impersonation
- Attachment requests
- Sender identification
1755802200_96.eml:
- Personal data requests
- Generic greetings
- Urgency/threats
- Service notifications
- Link click requests
1755802200_255.eml:
- Mention of postponed call
- Product offers
- Personalized greetings
- Sender identification
1755802200_23.eml:
- Generic greetings
- Product offers
- Explicit money amounts
- Sender identification
- Link click requests
1755802200_232.eml:
- Work with documents
- Sender identification
- Attachment requests
- Generic greetings
1755802200_237.eml:
- Sender identification
- Service notifications
- Urgency/threats
- Government impersonation
- No-confirmation requests
1755802200_107.eml:
- Service notifications
- Urgency/threats
- Sender identification
- Attachment requests
1755802200_120.eml:
- Urgency/threats
- Work with documents
1755802200_129.eml:
- Sender identification
1755802200_140.eml:
- Sender identification
- Generic greetings
- Surveys and voting
- Colleague/authority impersonation
- Link click requests
1755802200_185.eml:
- Colleague/authority impersonation
- Work with documents
- Generic greetings
- Mention of postponed call
- Attachment requests
- Sender identification
1755802200_197.eml:
- Financial operations
- Generic greetings
- Product offers
- Explicit money amounts
- Contests/prizes
- Link click requests
- Surveys and voting
1755802200_100.eml:
- HR messages
- Work with documents
- Personal data requests
- Attachment requests
- Generic greetings
1755802200_258.eml:
- Product offers
- Explicit money amounts
1755802200_261.eml:
- Attachment requests
- Urgency/threats
1755802200_266.eml:
- Work with documents
- No-confirmation requests
- Generic greetings
- Sender identification
1755802200_269.eml:
- Work with documents
- Personalized greetings
- Attachment requests
- Sender identification
1755802200_270.eml:
- Personalized greetings
- Attachment requests
- Link click requests
- Sender identification
1755802200_132.eml:
- Colleague/authority impersonation
- Work with documents
- Attachment requests
- Generic greetings
- Sender identification
1755802200_135.eml:
- Personalized greetings
1755802200_14.eml:
- Generic greetings
- Product offers
- Sender identification
- Link click requests
1755802200_114.eml:
- Colleague/authority impersonation
- Work with documents
- Link click requests
- Attachment requests
- Generic greetings
- Explicit money amounts
- Sender identification
1755802200_80.eml:
- Attachment requests
- Generic greetings
- Personal data requests
- Mention of postponed call
- Work with documents
- Sender identification
