data_handler:
  base_run_name: "NEWRU_NEWGS"
  get_synthetic_df: true
  get_balanced_df: true
  balancer_mode: kmeans # kmeans | maxmin
  target_trigger_count: 1000
  res_col: "res_vector"
  res_col_sent: "res_vec_sent"
  test_size: 0.15
  dh_verbose: true
  use_manual_ds: true
  encoder_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  sim_threshold: 0.9
  strat_order: 5

model_settings:
  encoder_name_default: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  target_strategy: "multi-output"

  hyperparameter_search: false
  hp_trials: 100
  hp_mode: "both" # encoder | head | both

training_args:
  finetune_args:
    num_epochs: 1
    num_iterations: 2
    batch_size: 16
    body_learning_rate: 5.652426360039554e-05
    warmup_proportion: 0.2903490123609603
    l2_weight: 3.844559355532281e-06
    logging_steps: 1000
    output_dir: checkpoints

  head_args:
    type: "logreg" # catboost | logreg | rf
    catboost:
      iterations: 1400
      learning_rate: 0.09601556853267823
      depth: 5
      l2_leaf_reg: 2.612581145672209
      border_count: 124
      bagging_temperature: 0.8066779844157292
      random_strength: 0.4177776718645092
      eval_metric: "F1"
    rf:
      n_estimators: 400
      max_depth: 17
      min_samples_split: 12
      min_samples_leaf: 3
    logreg:
      C: 1.5925104448230785
      solver: "lbfgs"
      max_iter: 137
      fit_intercept: true
      class_weight: null
